name: linear_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  window_manager: ^0.3.6
  fraction: ^5.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_phoenix: ^1.1.1
  file_selector: ^1.0.1
  icons_launcher: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


# [!] Dont add '.app_icons' folder to your pubspec assets! 
# This will lead to an unnecessary increase size of the application.
icons_launcher:
  platforms:
    android:
      enable: true
      adaptive_background_color: '#ffffff'
      adaptive_foreground_image: 'assets/.app_icons/android/foreground.png'
      image_path: 'assets/.app_icons/rectangle.png'
    ios:
      enable: true
      image_path: 'assets/.app_icons/rectangle.png'
    windows:
      enable: true
      image_path: 'assets/.app_icons/rectangle.png'
